### ISSUE TITLE
tool install can't find package in private NuGet feed

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/cli#12888]
## Steps to reproduce
1. Create an Azure Artifacts feed
2. Push a pre-release global tool to the feed
3. Click "Connect Feed" to get URL
4. Set up Feed in VS to see that the package does exist and is marked pre-release
5. Install the tool via Azure Pipelines

```yaml
  - task: NuGetCommand@2
    displayName: 'Add auth values'
    inputs:
      command: custom
      arguments: sources update -Name "SomeName" -Username "vsts" -Password "$(System.AccessToken)" -StorePasswordInClearText -ConfigFile NuGet.Config
   
  - pwsh: cat Nuget.config

  - pwsh: dotnet tool install --global ToolName --version 1.0.1-ci-20191014-185132 --configfile NuGet.config
```

## Expected  behavior

Tool is successfully installed.

## Actual behavior

Receive an error that package can't be found:

> error NU1101: Unable to find package ToolName. No packages exist with this id in source(s): FeedName, C:\Program Files\dotnet\sdk\NuGetFallbackFolder
> The tool package could not be restored.
> Tool 'ToolName' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name was found, but it was not a .NET Core tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.
> 
> For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
> ##[debug]$LASTEXITCODE: 1
> 

Not getting a 401 anymore, so auth doesn't appear to be the problem.

NuGet.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
   <packageSources>
      <add key="FeedName" value="https://OrgName.pkgs.visualstudio.com/_packaging/FeedName/nuget/v3/index.json" />
   </packageSources>
  <packageSourceCredentials>
    <FeedName>
      <add key="Username" value="vsts" />
      <add key="ClearTextPassword" value=*** />
    </FeedName>
  </packageSourceCredentials>
</configuration>
```

The package name and version are definitely correct. Am I missing something? Is there a better way to do this?

## Environment data
Azure DevOps
dotnet SDK 3.0.100

@wli3
