### ISSUE TITLE
dotnet-install.ps1 change breaks installation

### ISSUE THREAD

**Issue by jskeet** [dotnet/cli#4712]
Commit b2a83e0072566ea2ff4405c2c0c51cbfcca21c70 includes a call to `Get-Item $InstallRoot`.

That means that if the installation root doesn't already exist - which it's clearly not always expected to, given the later line of

```
New-Item -ItemType Directory -Force -Path $InstallRoot | Out-Null
```

... the installation fails:

> Get-Item : Cannot find path 'C:\Users\skeet\Downloads\.dotnetcli' because it does not exist.

This broke my AppVeyor CI build script, which includes:

```
install:
  - mkdir .\scripts
  - curl -SL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1 -o .\scripts\dotnet-install.ps1
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\dotnet-install.ps1 -InstallDir "$env:DOTNET_INSTALL_DIR" -Version 1.0.0-preview2-003121 -NoPath'
```

I strongly suspect many other people will have very similar CI installation scripts.

It feels to me like more smoke testing is required for changes to `dotnet-install.ps1`
