### ISSUE TITLE
Docker CI build fails due to Service failed to build: COPY failed

### ISSUE THREAD

**Issue by Murtain** [dotnet/cli#8099]
## Steps to reproduce

This is happening on Gitlab CI Runners (using their Docker shared runners - I'm using Gitlab for private projects and Docker  support):

```
docker ps
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS                  PORTS                                                               NAMES
38db8a517610        gitlab/gitlab-ce:latest   "/assets/wrapper"   35 hours ago        Up 23 hours (healthy)   0.0.0.0:2222->22/tcp, 0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp   gitlab

```

## Expected  behavior
I expected the project to build /publish normally.
## Actual behavior

```
Service 'murtain.oauth2' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder211242972/obj/Docker/publish: no such file or directory
ERROR: Job failed: exit code 1
```

## Environment data

`docker-compose.ci.build.yml`
```
version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Murtain.OAuth2.sln && dotnet publish ./Murtain.OAuth2.sln -c Release -o ./obj/Docker/publish"
```
`Dockerfile `

```
FROM microsoft/aspnetcore:2.0
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "Murtain.OAuth2.dll"]

```

`gitlab.ci.yml`

```
image: tmaier/docker-compose

stages:
- build
- deploy

before_script:
- docker --version
- docker-compose --version

build:
  stage: build
  script:
    - ls
    - cd Murtain.OAuth2
    - ls
    - docker-compose -f docker-compose.ci.build.yml up
    
  
deploy:
  stage: deploy
  script:
    - ls
    - cd Murtain.OAuth2
    - ls
    - dotnet info
    - docker-compose -f docker-compose.yml up
  only:
    - master

```

job-build :

```
Running with gitlab-runner 10.2.0 (0a75cdd1)
  on gitlab runner (812d076a)
Using Docker executor with image tmaier/docker-compose ...
Using docker image sha256:ead09bd5e3f0fcb60614d4eb5e6dcd75da8274e5c86e6b63954956315b2f8a15 for predefined container...
Pulling docker image tmaier/docker-compose ...
Using docker image tmaier/docker-compose ID=sha256:c58b8bbe54fb1e8c0181e9669474a3598788e61ccf12f12c66aca44cfc6d95f0 for build container...
Running on runner-812d076a-project-3-concurrent-0 via izl88djldhqpnez...
Fetching changes...
HEAD is now at 5976156 Update .gitlab-ci.yml
From http://git.x-dva.com/dev/Murtain.OAuth2
   5976156..2003196  master     -> origin/master
Checking out 20031962 as master...
Skipping Git submodules setup
$ docker --version
Docker version 17.11.0-ce, build 1caf76c
$ docker-compose --version
docker-compose version 1.17.1, build 6d101fb
$ ls
Murtain.OAuth2
$ cd Murtain.OAuth2
$ ls
Murtain.OAuth2
Murtain.OAuth2.sln
docker-compose.ci.build.yml
docker-compose.dcproj
docker-compose.override.yml
docker-compose.yml
$ docker-compose -f docker-compose.ci.build.yml up
Starting murtainoauth2_ci-build_1 ... 
Starting murtainoauth2_ci-build_1

Starting murtainoauth2_ci-build_1 ... done
Attaching to murtainoauth2_ci-build_1
ci-build_1  | MSBUILD : error MSB1009: Project file does not exist.
ci-build_1  | Switch: ./Murtain.OAuth2.sln
murtainoauth2_ci-build_1 exited with code 1
Job succeeded
```
job-deploy:
```
Running with gitlab-runner 10.2.0 (0a75cdd1)
  on gitlab runner (812d076a)
Using Docker executor with image tmaier/docker-compose ...
Using docker image sha256:ead09bd5e3f0fcb60614d4eb5e6dcd75da8274e5c86e6b63954956315b2f8a15 for predefined container...
Pulling docker image tmaier/docker-compose ...
Using docker image tmaier/docker-compose ID=sha256:c58b8bbe54fb1e8c0181e9669474a3598788e61ccf12f12c66aca44cfc6d95f0 for build container...
Running on runner-812d076a-project-3-concurrent-0 via izl88djldhqpnez...
Fetching changes...
HEAD is now at 2003196 Update .gitlab-ci.yml
Checking out 20031962 as master...
Skipping Git submodules setup
$ docker --version
Docker version 17.11.0-ce, build 1caf76c
$ docker-compose --version
docker-compose version 1.17.1, build 6d101fb
$ ls
Murtain.OAuth2
$ cd Murtain.OAuth2
$ ls
Murtain.OAuth2
Murtain.OAuth2.sln
docker-compose.ci.build.yml
docker-compose.dcproj
docker-compose.override.yml
docker-compose.yml
$ docker-compose -f docker-compose.yml up
Building murtain.oauth2
Step 1/6 : FROM microsoft/aspnetcore:2.0
 ---> 01d033b55240
Step 2/6 : ARG source
 ---> Using cache
 ---> 3ef5453f13f6
Step 3/6 : WORKDIR /app
 ---> Using cache
 ---> 985696166e6f
Step 4/6 : EXPOSE 80
 ---> Using cache
 ---> 5c63d0729cc7
Step 5/6 : COPY ${source:-obj/Docker/publish} .
Service 'murtain.oauth2' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder211242972/obj/Docker/publish: no such file or directory
ERROR: Job failed: exit code 1
```

**Comment by livarcocc** [comment]
It fails to publish because it can't find your sln file:

```
ci-build_1  | MSBUILD : error MSB1009: Project file does not exist.
ci-build_1  | Switch: ./Murtain.OAuth2.sln
```

Seems like you need to fix your dockers files to make sure that the dotnet command can access your sln file.

**Comment by Murtain** [comment]
@livarcocc Thank you for reminding me。

And then I changed the `docker-compose.ci.build.yml`  
```
version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0
    container_name: build-env
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet --version && ls -a "

```
job-build:
```
Using docker image sha256:ead09bd5e3f0fcb60614d4eb5e6dcd75da8274e5c86e6b63954956315b2f8a15 for predefined container...
Pulling docker image tmaier/docker-compose ...
Using docker image tmaier/docker-compose ID=sha256:c58b8bbe54fb1e8c0181e9669474a3598788e61ccf12f12c66aca44cfc6d95f0 for build container...
Running on runner-812d076a-project-3-concurrent-0 via izl88djldhqpnez...
Fetching changes...
HEAD is now at b2101f4 Update docker-compose.ci.build.yml
From http://git.x-dva.com/dev/Murtain.OAuth2
   b2101f4..8ec8144  master     -> origin/master
Checking out 8ec8144b as master...
Skipping Git submodules setup
$ docker --version
Docker version 17.11.0-ce, build 1caf76c
$ docker-compose --version
docker-compose version 1.17.1, build 6d101fb
$ ls
Murtain.OAuth2
$ cd Murtain.OAuth2
$ ls
Murtain.OAuth2
Murtain.OAuth2.sln
docker-compose.ci.build.yml
docker-compose.dcproj
docker-compose.override.yml
docker-compose.yml
$ docker-compose logs &&  docker-compose -f docker-compose.ci.build.yml up
Attaching to 
Recreating murtainoauth2_ci-build_1 ... 
Recreating murtainoauth2_ci-build_1

Recreating murtainoauth2_ci-build_1 ... done
Attaching to build-env
build-env   | 2.0.3
build-env   | .
build-env   | ..
build-env exited with code 0
Job succeeded

```

the same command in local:

```
[root@izl88djldhqpnez Murtain.OAuth2]# docker-compose -f docker-compose.ci.build.yml up
Recreating murtainoauth2_ci-build_1 ...
Recreating murtainoauth2_ci-build_1 ... done
Attaching to murtainoauth2_ci-build_1
ci-build_1  | 2.0.3
ci-build_1  | .
ci-build_1  | ..
ci-build_1  | .vs
ci-build_1  | Murtain.OAuth2
ci-build_1  | Murtain.OAuth2.sln
ci-build_1  | docker-compose.ci.build.yml
ci-build_1  | docker-compose.dcproj
ci-build_1  | docker-compose.override.yml
ci-build_1  | docker-compose.yml
murtainoauth2_ci-build_1 exited with code 0
```
Why is there no copy in the container in gitlab-runner? Do I need to do something extra?
